import type { Product, ProductVariation, CartItem } from '../types';

export const mockVariation5mg: ProductVariation = {
  id: 'var-1',
  product_id: 'prod-1',
  name: '5mg',
  quantity_mg: 5,
  price: 1500,
  disposable_pen_price: null,
  reusable_pen_price: null,
  discount_price: null,
  discount_active: false,
  stock_quantity: 10,
  created_at: '2024-01-01T00:00:00Z',
};

export const mockVariation10mg: ProductVariation = {
  id: 'var-2',
  product_id: 'prod-1',
  name: '10mg',
  quantity_mg: 10,
  price: 2500,
  disposable_pen_price: null,
  reusable_pen_price: null,
  discount_price: 2000,
  discount_active: true,
  stock_quantity: 5,
  created_at: '2024-01-01T00:00:00Z',
};

export const mockVariationOutOfStock: ProductVariation = {
  id: 'var-3',
  product_id: 'prod-1',
  name: '15mg',
  quantity_mg: 15,
  price: 3500,
  disposable_pen_price: null,
  reusable_pen_price: null,
  discount_price: null,
  discount_active: false,
  stock_quantity: 0,
  created_at: '2024-01-01T00:00:00Z',
};

export const mockProduct: Product = {
  id: 'prod-1',
  name: 'Tirzepatide',
  description: 'Research-grade Tirzepatide peptide',
  category: 'weight-loss',
  base_price: 2000,
  discount_price: 1500,
  discount_start_date: null,
  discount_end_date: null,
  discount_active: true,
  purity_percentage: 99.5,
  molecular_weight: '4813.45',
  cas_number: '2023788-19-2',
  sequence: 'YXEGTFTSDYSIXLDKIAQKAFVQWLIAGGPSSGAPPPS',
  storage_conditions: 'Store at -20°C',
  inclusions: ['Certificate of Analysis', 'HPLC Report'],
  stock_quantity: 20,
  available: true,
  featured: true,
  image_url: 'https://example.com/tirzepatide.jpg',
  safety_sheet_url: null,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  variations: [mockVariation5mg, mockVariation10mg],
};

export const mockProductNoDiscount: Product = {
  id: 'prod-2',
  name: 'BPC-157',
  description: 'Body Protection Compound-157',
  category: 'healing',
  base_price: 1200,
  discount_price: null,
  discount_start_date: null,
  discount_end_date: null,
  discount_active: false,
  purity_percentage: 98.5,
  molecular_weight: '1419.53',
  cas_number: '137525-51-0',
  sequence: null,
  storage_conditions: 'Store at -20°C',
  inclusions: null,
  stock_quantity: 15,
  available: true,
  featured: false,
  image_url: null,
  safety_sheet_url: null,
  created_at: '2024-01-02T00:00:00Z',
  updated_at: '2024-01-02T00:00:00Z',
  variations: [],
};

export const mockProductOutOfStock: Product = {
  id: 'prod-3',
  name: 'Semaglutide',
  description: 'Research-grade Semaglutide peptide',
  category: 'weight-loss',
  base_price: 3000,
  discount_price: null,
  discount_start_date: null,
  discount_end_date: null,
  discount_active: false,
  purity_percentage: 99.0,
  molecular_weight: '4113.58',
  cas_number: '910463-68-2',
  sequence: null,
  storage_conditions: 'Store at 2-8°C',
  inclusions: null,
  stock_quantity: 0,
  available: true,
  featured: false,
  image_url: null,
  safety_sheet_url: null,
  created_at: '2024-01-03T00:00:00Z',
  updated_at: '2024-01-03T00:00:00Z',
  variations: [],
};

export const mockProductUnavailable: Product = {
  id: 'prod-4',
  name: 'TB-500',
  description: 'Thymosin Beta-4 peptide',
  category: 'healing',
  base_price: 1800,
  discount_price: null,
  discount_start_date: null,
  discount_end_date: null,
  discount_active: false,
  purity_percentage: 97.0,
  molecular_weight: '4963.5',
  cas_number: '77591-33-4',
  sequence: null,
  storage_conditions: 'Store at -20°C',
  inclusions: null,
  stock_quantity: 10,
  available: false,
  featured: false,
  image_url: null,
  safety_sheet_url: null,
  created_at: '2024-01-04T00:00:00Z',
  updated_at: '2024-01-04T00:00:00Z',
  variations: [],
};

export const mockCartItem: CartItem = {
  product: mockProduct,
  variation: mockVariation5mg,
  quantity: 2,
};

export const mockCartItemNoVariation: CartItem = {
  product: mockProductNoDiscount,
  variation: undefined,
  quantity: 1,
};
